import type { NextPage } from 'next';
import Head from 'next/head';
import HomePage from '../screens/home';

const Home: NextPage = () => (
  <div style={{ width: '100%', height: '100vh' }}>
    <Head>
      <title>Doome</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <HomePage />

  </div>
);

export default Home;
